- name: L2
  hosts: webservers
  tasks:
    - name: Create User and Group
      become: yes
      block:
        - name: Create group
          group: 
            name: "{{ user.group }}"

        - name: Create user
          user:
            name: "{{ user.login }}"
            password: "{{ user.password | password_hash('sha512') }}"
            shell: /bin/bash
            group: "{{ user.group }}"
      rescue:
        - name: Rollback changes if need
          command: date

    - name: Create directory
      file:
        path: "/home/{{ user.login }}/{{ file.name }}"
        state=directory

    - name: Install
      become: yes
      package:
        name:
          - htop
          - mc
	  - unzip
        state: latest
      apt:
        name: nginx

    - name: Download file
      get_url:
        url: https://i.ytimg.com/vi/G1IbRujko-A/maxresdefault.jpg
        dest: /home/{{ user.login }}/{{ file.name }}
        mode: '0777'

